In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, 13].values
X
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [4]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [6]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [8]:
a=X[:,1]

In [9]:
a

array([0, 2, 0, ..., 0, 1, 0], dtype=object)

In [10]:
import tensorflow as tf


In [11]:
#np.set_printoptions(threshold=None)

In [12]:
from keras.utils import to_categorical
encoded = to_categorical(a)
print(encoded[0:5])
c=encoded[:,[1,2]]
print(c[0:5])

Using TensorFlow backend.


[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 1.]]


In [13]:
b=np.append(c,X, axis=1)
b[0:5]


array([[0.0, 0.0, 619, 0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [0.0, 1.0, 608, 2, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [0.0, 0.0, 502, 0, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [0.0, 0.0, 699, 0, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [0.0, 1.0, 850, 2, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1]],
      dtype=object)

In [14]:
b=np.delete(b,3,1)
b[0:5]


array([[0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [0.0, 1.0, 608, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [0.0, 0.0, 502, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [0.0, 0.0, 699, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [0.0, 1.0, 850, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1]],
      dtype=object)

In [15]:
X=b
X

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)


In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


C:\Users\Prasoon\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Prasoon\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Prasoon\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [18]:
X_train.shape

(7500, 11)

In [19]:
X_test.shape

(2500, 11)

In [20]:
X_train[0:5]

array([[ 1.76021608, -0.57468161, -0.73550706, -1.08726059,  0.01526571,
         0.00886037,  0.67316003,  2.53503394, -1.55362351, -1.03446007,
        -1.64080994],
       [-0.56811207, -0.57468161,  1.02442719, -1.08726059, -0.65260917,
         0.00886037, -1.20772417,  0.80424154,  0.64365658, -1.03446007,
        -0.07927152],
       [-0.56811207,  1.74009395,  0.80829492, -1.08726059, -0.46178778,
         1.39329338, -0.35693706,  0.80424154,  0.64365658,  0.96668786,
        -0.99684012],
       [-0.56811207,  1.74009395,  0.39661439,  0.91974271, -0.08014499,
         0.00886037, -0.00935627, -0.92655087,  0.64365658,  0.96668786,
        -1.5917461 ],
       [-0.56811207, -0.57468161, -0.46791471,  0.91974271,  1.25560478,
         0.70107688, -1.20772417,  0.80424154,  0.64365658,  0.96668786,
         1.28330241]])

In [21]:
import keras

In [22]:
from keras.models import Sequential

In [23]:
from keras.layers import Dense,Dropout

In [24]:
model=Sequential()

In [25]:
model.add(Dense(6,input_shape=(11,),activation='relu'))
model.add(Dropout(0.1))

In [26]:
model.add(Dense(6,activation='relu'))
model.add(Dropout(0.1))

In [27]:
model.add(Dense(1,activation='sigmoid'))

In [28]:
model.compile('adam', loss='binary_crossentropy', metrics=['accuracy'])

In [62]:
model.fit(X_train,y_train,batch_size=10, epochs=10,validation_split=0.1)

Train on 6750 samples, validate on 750 samples
Epoch 1/10
6750/6750 [==============================] - 6s 917us/step - loss: 0.5773 - acc: 0.7330 - val_loss: 0.4675 - val_acc: 0.7960
Epoch 2/10
6750/6750 [==============================] - 4s 606us/step - loss: 0.4678 - acc: 0.7978 - val_loss: 0.4326 - val_acc: 0.7960
Epoch 3/10
6750/6750 [==============================] - 4s 569us/step - loss: 0.4547 - acc: 0.8022 - val_loss: 0.4169 - val_acc: 0.8013
Epoch 4/10
6750/6750 [==============================] - 4s 561us/step - loss: 0.4456 - acc: 0.8050 - val_loss: 0.4058 - val_acc: 0.8093
Epoch 5/10
6750/6750 [==============================] - 4s 574us/step - loss: 0.4291 - acc: 0.8095 - val_loss: 0.3934 - val_acc: 0.8267
Epoch 6/10
6750/6750 [==============================] - 4s 582us/step - loss: 0.4208 - acc: 0.8207 - val_loss: 0.3830 - val_acc: 0.8253
Epoch 7/10
6750/6750 [==============================] - 4s 553us/step - loss: 0.4119 - acc: 0.8172 - val_loss: 0.3777 - val_acc: 0.8280
E

In [63]:
y_pred=model.predict(X_test)

In [64]:
y_pred=(y_pred>0.5)

In [65]:
from sklearn.metrics import confusion_matrix

In [66]:
cm=confusion_matrix(y_test,y_pred)

In [67]:
cm

array([[1936,   55],
       [ 335,  174]], dtype=int64)

In [68]:
(1871+268)/(1871+268+120+241)

0.8556

In [69]:
X

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [70]:
X

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [71]:
new_model=model.predict(sc.transform(np.array([[0,0,600,1,40,3,60000,2,1,1,50000]])))

C:\Users\Prasoon\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [72]:
new_model=(new_model>0.5)

In [73]:
new_model

array([[False]])

In [29]:
#import talos as ta


In [28]:
optimizers = ['rmsprop', 'adam']
epochs = [10]
batches = [5, 10,]
param_grid = dict(optimizer=optimizers, epochs=epochs, batch_size=batches)

In [29]:
def my_model(optimizer='rmsprop'):

         model = Sequential()
         model.add(Dense(6,input_shape=(11,),activation='relu'))
         model.add(Dropout(0.1))
         model.add(Dense(6,activation='relu'))
         model.add(Dropout(0.1))
         model.add(Dense(1,activation='sigmoid'))
         model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])
         #out=model.fit(X_train,y_train,batch_size=params['batch_size'], epochs=params['epochs'],validation_split=0.1)

         return  model

In [33]:
#scan_object = ta.Scan(X, y, model=model, params=params, grid_downsample=0.1)


  0%|                                                                                            | 0/1 [00:00<?, ?it/s]

Train on 6300 samples, validate on 700 samples
Epoch 1/20
6300/6300 [==============================] - ETA: 9:59 - loss: 0.5431 - acc: 0.700 - ETA: 1:06 - loss: 0.5537 - acc: 0.722 - ETA: 40s - loss: 0.5838 - acc: 0.710 - ETA: 32s - loss: 0.5554 - acc: 0.74 - ETA: 23s - loss: 0.5533 - acc: 0.75 - ETA: 16s - loss: 0.5404 - acc: 0.77 - ETA: 13s - loss: 0.5374 - acc: 0.78 - ETA: 11s - loss: 0.5353 - acc: 0.78 - ETA: 10s - loss: 0.5305 - acc: 0.78 - ETA: 9s - loss: 0.5321 - acc: 0.7831 - ETA: 9s - loss: 0.5292 - acc: 0.784 - ETA: 8s - loss: 0.5228 - acc: 0.787 - ETA: 7s - loss: 0.5192 - acc: 0.787 - ETA: 6s - loss: 0.5176 - acc: 0.787 - ETA: 5s - loss: 0.5137 - acc: 0.791 - ETA: 5s - loss: 0.5155 - acc: 0.790 - ETA: 5s - loss: 0.5151 - acc: 0.790 - ETA: 4s - loss: 0.5138 - acc: 0.790 - ETA: 4s - loss: 0.5142 - acc: 0.790 - ETA: 4s - loss: 0.5168 - acc: 0.789 - ETA: 3s - loss: 0.5144 - acc: 0.789 - ETA: 3s - loss: 0.5155 - acc: 0.790 - ETA: 3s - loss: 0.5152 - acc: 0.790 - ETA: 3s - loss: 0

6300/6300 [==============================] - ETA: 3s - loss: 0.3898 - acc: 0.900 - ETA: 1s - loss: 0.5396 - acc: 0.770 - ETA: 2s - loss: 0.4991 - acc: 0.797 - ETA: 1s - loss: 0.4915 - acc: 0.801 - ETA: 1s - loss: 0.4858 - acc: 0.808 - ETA: 1s - loss: 0.4809 - acc: 0.814 - ETA: 1s - loss: 0.4801 - acc: 0.814 - ETA: 1s - loss: 0.4882 - acc: 0.810 - ETA: 1s - loss: 0.4830 - acc: 0.814 - ETA: 1s - loss: 0.4855 - acc: 0.814 - ETA: 1s - loss: 0.4949 - acc: 0.807 - ETA: 1s - loss: 0.4924 - acc: 0.809 - ETA: 1s - loss: 0.4940 - acc: 0.808 - ETA: 1s - loss: 0.5008 - acc: 0.803 - ETA: 1s - loss: 0.4985 - acc: 0.803 - ETA: 1s - loss: 0.4968 - acc: 0.805 - ETA: 1s - loss: 0.4962 - acc: 0.805 - ETA: 1s - loss: 0.4975 - acc: 0.804 - ETA: 1s - loss: 0.4998 - acc: 0.802 - ETA: 1s - loss: 0.4978 - acc: 0.804 - ETA: 1s - loss: 0.5002 - acc: 0.803 - ETA: 1s - loss: 0.4982 - acc: 0.804 - ETA: 1s - loss: 0.4949 - acc: 0.806 - ETA: 1s - loss: 0.4951 - acc: 0.805 - ETA: 1s - loss: 0.4954 - acc: 0.805 - ETA: 

6300/6300 [==============================] - ETA: 2s - loss: 0.5545 - acc: 0.750 - ETA: 3s - loss: 0.4906 - acc: 0.808 - ETA: 3s - loss: 0.4842 - acc: 0.809 - ETA: 3s - loss: 0.5003 - acc: 0.796 - ETA: 3s - loss: 0.5095 - acc: 0.797 - ETA: 3s - loss: 0.5150 - acc: 0.792 - ETA: 2s - loss: 0.5227 - acc: 0.782 - ETA: 2s - loss: 0.5169 - acc: 0.788 - ETA: 2s - loss: 0.5123 - acc: 0.790 - ETA: 2s - loss: 0.5156 - acc: 0.787 - ETA: 1s - loss: 0.5169 - acc: 0.786 - ETA: 1s - loss: 0.5102 - acc: 0.792 - ETA: 1s - loss: 0.5027 - acc: 0.797 - ETA: 1s - loss: 0.5008 - acc: 0.798 - ETA: 1s - loss: 0.4942 - acc: 0.804 - ETA: 1s - loss: 0.5003 - acc: 0.800 - ETA: 1s - loss: 0.4992 - acc: 0.800 - ETA: 1s - loss: 0.4969 - acc: 0.802 - ETA: 1s - loss: 0.4939 - acc: 0.803 - ETA: 1s - loss: 0.4930 - acc: 0.804 - ETA: 1s - loss: 0.4947 - acc: 0.803 - ETA: 1s - loss: 0.4960 - acc: 0.803 - ETA: 1s - loss: 0.4951 - acc: 0.803 - ETA: 1s - loss: 0.4947 - acc: 0.803 - ETA: 0s - loss: 0.4968 - acc: 0.802 - ETA: 

100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:53<00:00, 53.29s/it]


Scan Finished!


In [30]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

In [31]:
model=KerasClassifier(build_fn=my_model)
grid=GridSearchCV(estimator=model,param_grid=param_grid,scoring='accuracy',cv=10)#cv=no. of folds


In [32]:
grid_result=grid.fit(X_train,y_train)

Epoch 1/10
6750/6750 [==============================] - 8s 1ms/step - loss: 0.5216 - acc: 0.7836
Epoch 2/10
6750/6750 [==============================] - 7s 1ms/step - loss: 0.4581 - acc: 0.8028
Epoch 3/10
6750/6750 [==============================] - 7s 1ms/step - loss: 0.4477 - acc: 0.8096
Epoch 4/10
6750/6750 [==============================] - 7s 1ms/step - loss: 0.4356 - acc: 0.8124
Epoch 5/10
6750/6750 [==============================] - 7s 1ms/step - loss: 0.4350 - acc: 0.8142
Epoch 6/10
6750/6750 [==============================] - 7s 1ms/step - loss: 0.4266 - acc: 0.8197
Epoch 7/10
6750/6750 [==============================] - 7s 1ms/step - loss: 0.4291 - acc: 0.8173
Epoch 8/10
6750/6750 [==============================] - ETA: 0s - loss: 0.4262 - acc: 0.818 - 7s 1ms/step - loss: 0.4259 - acc: 0.8191
Epoch 9/10
6750/6750 [==============================] - 7s 1ms/step - loss: 0.4223 - acc: 0.8190
Epoch 10/10
6750/6750 [==============================] - 7s 1ms/step - loss: 0.4231 - acc

Epoch 4/10
6750/6750 [==============================] - 9s 1ms/step - loss: 0.4424 - acc: 0.7960
Epoch 5/10
6750/6750 [==============================] - 8s 1ms/step - loss: 0.4381 - acc: 0.8187
Epoch 6/10
6750/6750 [==============================] - 8s 1ms/step - loss: 0.4320 - acc: 0.8204
Epoch 7/10
6750/6750 [==============================] - 9s 1ms/step - loss: 0.4275 - acc: 0.8207
Epoch 8/10
6750/6750 [==============================] - 9s 1ms/step - loss: 0.4251 - acc: 0.8193
Epoch 9/10
6750/6750 [==============================] - 9s 1ms/step - loss: 0.4183 - acc: 0.8221
Epoch 10/10
6750/6750 [==============================] - 8s 1ms/step - loss: 0.4203 - acc: 0.8210
Epoch 1/10
6750/6750 [==============================] - 8s 1ms/step - loss: 0.5322 - acc: 0.7653
Epoch 2/10
6750/6750 [==============================] - 6s 919us/step - loss: 0.4573 - acc: 0.8016
Epoch 3/10
6750/6750 [==============================] - 6s 940us/step - loss: 0.4444 - acc: 0.8123
Epoch 4/10
6750/6750 [===

6750/6750 [==============================] - 10s 1ms/step - loss: 0.4263 - acc: 0.8175
Epoch 6/10
6750/6750 [==============================] - 10s 1ms/step - loss: 0.4201 - acc: 0.8191
Epoch 7/10
6750/6750 [==============================] - 10s 1ms/step - loss: 0.4194 - acc: 0.8190
Epoch 8/10
6750/6750 [==============================] - 10s 1ms/step - loss: 0.4164 - acc: 0.8207
Epoch 9/10
6750/6750 [==============================] - 10s 1ms/step - loss: 0.4180 - acc: 0.8185
Epoch 10/10
6750/6750 [==============================] - 11s 2ms/step - loss: 0.4150 - acc: 0.8216
Epoch 1/10
6750/6750 [==============================] - 14s 2ms/step - loss: 0.4974 - acc: 0.7833
Epoch 2/10
6750/6750 [==============================] - 10s 2ms/step - loss: 0.4562 - acc: 0.8009
Epoch 3/10
6750/6750 [==============================] - 10s 1ms/step - loss: 0.4461 - acc: 0.8010
Epoch 4/10
6750/6750 [==============================] - 8s 1ms/step - loss: 0.4364 - acc: 0.8000
Epoch 5/10
6750/6750 [=========

6750/6750 [==============================] - 5s 704us/step - loss: 0.4373 - acc: 0.8006
Epoch 8/10
6750/6750 [==============================] - 5s 699us/step - loss: 0.4355 - acc: 0.8055
Epoch 9/10
6750/6750 [==============================] - 6s 847us/step - loss: 0.4336 - acc: 0.8120
Epoch 10/10
6750/6750 [==============================] - 5s 707us/step - loss: 0.4302 - acc: 0.8170
Epoch 1/10
6750/6750 [==============================] - 9s 1ms/step - loss: 0.5648 - acc: 0.7551
Epoch 2/10
6750/6750 [==============================] - 5s 710us/step - loss: 0.4720 - acc: 0.7975
Epoch 3/10
6750/6750 [==============================] - 5s 712us/step - loss: 0.4584 - acc: 0.8018
Epoch 4/10
6750/6750 [==============================] - 5s 707us/step - loss: 0.4492 - acc: 0.8090
Epoch 5/10
6750/6750 [==============================] - 5s 678us/step - loss: 0.4345 - acc: 0.8188
Epoch 6/10
6750/6750 [==============================] - 4s 632us/step - loss: 0.4199 - acc: 0.8279
Epoch 7/10
6750/6750 [

6750/6750 [==============================] - 6s 877us/step - loss: 0.4291 - acc: 0.8124
Epoch 10/10
6750/6750 [==============================] - 6s 860us/step - loss: 0.4294 - acc: 0.8147
Epoch 1/10
6750/6750 [==============================] - 9s 1ms/step - loss: 0.5237 - acc: 0.7904
Epoch 2/10
6750/6750 [==============================] - 5s 705us/step - loss: 0.4611 - acc: 0.7976
Epoch 3/10
6750/6750 [==============================] - 5s 698us/step - loss: 0.4411 - acc: 0.8059
Epoch 4/10
6750/6750 [==============================] - 5s 698us/step - loss: 0.4309 - acc: 0.8136
Epoch 5/10
6750/6750 [==============================] - 5s 705us/step - loss: 0.4162 - acc: 0.8178
Epoch 6/10
6750/6750 [==============================] - 5s 701us/step - loss: 0.4080 - acc: 0.8197
Epoch 7/10
6750/6750 [==============================] - 5s 700us/step - loss: 0.4031 - acc: 0.8277
Epoch 8/10
6750/6750 [==============================] - 6s 849us/step - loss: 0.3940 - acc: 0.8317
Epoch 9/10
6750/6750 [

7500/7500 [==============================] - 6s 771us/step - loss: 0.4032 - acc: 0.8247


In [33]:
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
	print("%f (%f) with: %r" % (mean, stdev, param))

Best: 0.833600 using {'batch_size': 10, 'epochs': 10, 'optimizer': 'adam'}
0.829467 (0.013406) with: {'batch_size': 5, 'epochs': 10, 'optimizer': 'rmsprop'}
0.833067 (0.016512) with: {'batch_size': 5, 'epochs': 10, 'optimizer': 'adam'}
0.826533 (0.021961) with: {'batch_size': 10, 'epochs': 10, 'optimizer': 'rmsprop'}
0.833600 (0.015796) with: {'batch_size': 10, 'epochs': 10, 'optimizer': 'adam'}


In [34]:
grid.best_params_


{'batch_size': 10, 'epochs': 10, 'optimizer': 'adam'}

In [35]:
grid.best_score_

0.8336